apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: x0katflm1-go 
  janus-idp.io/tekton: x0katflm1-go
  backstage.io/kubernetes-id: x0katflm1-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x0katflm1-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml